name: thetulipmanager
description: An e-commerce orders management app.

publish_to: "none"

version: 1.0.0-beta.1 

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  animated_bottom_navigation_bar: ^1.1.0
  another_flushbar: ^1.12.29
  auto_route: ^5.0.4
  bottom_sheet: ^3.1.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_app_check: ^0.1.1+5
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  fluent_ui: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  iconsax: ^0.0.8
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kt_dart: ^1.0.0
  pin_code_fields: ^7.4.0
  rive: ^0.9.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  sqflite: ^2.2.1
  supabase: ^1.2.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  injectable_generator: ^2.1.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/animations/
    - assets/illustrations/
  fonts:
    - family: TheTulipFont
      fonts:
        - asset: assets/fonts/TheTulipFont.ttf
    - family: IconlyBold
      fonts:
        - asset: assets/fonts/IconlyBold.ttf
    - family: IconlyBroken
      fonts:
        - asset: assets/fonts/IconlyBroken.ttf

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/circle_logo.png

  # branding: assets/branding-development.png
  color_dark: "#000000"
  image_dark: assets/logos/circle_logo.png

  android_12:
    image: assets/logos/icon.png
    icon_background_color: "#FCE4EC"

    image_dark: assets/logos/icon.png
    icon_background_color_dark: "#FCE4EC"

  web: false
