name: thetulipmanager
description: An e-commerce orders management app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0
  another_flushbar: ^1.12.29
  auto_route: ^5.0.2
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_app_check: ^0.1.1+1
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  iconsax: ^0.0.8
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kt_dart: ^1.0.0
  pin_code_fields: ^7.4.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  supabase: ^1.0.1
  url_launcher: ^6.1.6
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.11
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator:
    git:
      url: https://github.com/amondnet/injectable.git
      path: injectable_generator
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/illustrations/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
  fonts:
    - family: TheTulipFont
      fonts:
        - asset: assets/fonts/TheTulipFont.ttf
    - family: IconlyBold
      fonts:
        - asset: assets/fonts/IconlyBold.ttf
    - family: IconlyBroken
      fonts:
        - asset: assets/fonts/IconlyBroken.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#FEF9FA"
  image: assets/logos/icon.png
  
  # branding: assets/branding-development.png
  color_dark: "#121212"
  image_dark: assets/logos/icon_white.png

  android_12:
    image: assets/logos/icon.png
    icon_background_color: "#FEF9FA"
    image_dark: assets/logos/icon_white.png
    icon_background_color_dark: "#121212"

  web: false
