// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8gCAvSH9oqrlZLtQoU8t2onICBIgR2Cw',
    appId: '1:81164748349:web:93ff6c3855c48705df0c54',
    messagingSenderId: '81164748349',
    projectId: 'tulip-manager',
    authDomain: 'tulip-manager.firebaseapp.com',
    storageBucket: 'tulip-manager.appspot.com',
    measurementId: 'G-R0K0Z7B5VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lyFk4bCi9w5OqceUKTqHsQcqzdl0AJM',
    appId: '1:81164748349:android:dd524bc69bdf97c5df0c54',
    messagingSenderId: '81164748349',
    projectId: 'tulip-manager',
    storageBucket: 'tulip-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPAqJZ7EelW4EIiCbl1tpWIXpBUxsx_g',
    appId: '1:81164748349:ios:c9ea572a117c3873df0c54',
    messagingSenderId: '81164748349',
    projectId: 'tulip-manager',
    storageBucket: 'tulip-manager.appspot.com',
    iosClientId: '81164748349-58pc67d8jst68g3hae3thsa7b7l33bpv.apps.googleusercontent.com',
    iosBundleId: 'com.amabelabbas.thetulipmanager',
  );
}
